#!/usr/bin/python

import sys
import time
import getopt
import fcntl

import lastfm
import lastfm.asyaml

if __name__ == "__main__":

    shortopts = 'o:'
    longopts = ['output=']

    outfile = lastfm.SUBMITD_FIFO

    try:
        opts, args = getopt.getopt(sys.argv[1:], shortopts, longopts)
    except getopt.GetoptError, e:
        print >>sys.stderr, "error: %s" % e
        sys.exit(1)

    for opt, arg in opts:
        if opt in ('--output', '-o'):
            outfile = arg

    tracks = []
    for f in [file(n) for n in args] or [sys.stdin]:
        input = lastfm.asyaml.Parser(f.read())
        tracks += [t for t in input.parse()]

    total_len = 0
    for track in tracks:
        total_len += track.length

    # We will simulate things as if the last track in our input just
    # finished playing right now.
    start = time.time() - total_len

    pos = start
    subs = []
    for track in tracks:
        if track.length == 0:
            print >>sys.stderr, "bad input: track has zero length"
            sys.exit(1)
        if track.length >= lastfm.MIN_LEN and track.length <= lastfm.MAX_LEN:
            date = pos + track.length / 2
            subs.append(lastfm.asyaml.Submission(track=track,
                time=time.gmtime(date)))
            pos += track.length

    subs_enc = "\n".join([str(s) for s in subs])
    if outfile == "-":
        print subs_enc
    else:
        try:
            out = file(outfile, 'w')
            log.debug("Requesting lock on %s" % outfile)
            fcntl.flock(out, fcntl.LOCK_EX)
            print >>out, subs_enc
            fcntl.flock(out, fcntl.LOCK_UN)
            log.info("Queued %s subs", len(subs))
        except IOError:
            print >>sys.stderr, "error: could not write to %s" % outfile
