#!/usr/bin/python

import sys
import time
import getopt

import lastfm
import lastfm.logger
import lastfm.queue
import lastfm.marshaller

if __name__ == "__main__":
    shortopts = 'o:d'
    longopts = ['output=', 'debug']

    try:
        opts, args = getopt.getopt(sys.argv[1:], shortopts, longopts)
    except getopt.GetoptError, e:
        print >>sys.stderr, "error: %s" % e
        sys.exit(1)

    debug = False
    outfile = lastfm.SUBMITD_FIFO

    for opt, arg in opts:
        if opt in ('--output', '-o'):
            outfile = arg
        elif opt in ('--debug', '-d'):
            debug = True
        else:
            print >>sys.stderr, "unknown option: %s", opt
            sys.exit(1)

    log = lastfm.logger.create_log("lastcdreplay", debug)

    tracks = []
    for f in [file(name) for name in args] or [sys.stdin]:
        for track in lastfm.marshaller.load_documents(f.read()):
            tracks.append(track)

    len = 0
    for t in tracks:
        len += t['length']

    # We will simulate things as if the last track in our input just
    # finished playing right now.

    pos = time.time() - len

    subs = []
    for t in tracks:
        len = t['length']
        if len:
            if len >= lastfm.MIN_LEN and len <= lastfm.MAX_LEN:
                date = pos + len / 2
                t['time'] = time.gmtime(pos)
                subs.append(t)
            pos = pos + len
        else:
            print >>sys.stderr, "all tracks must have a non-zero length"
            sys.exit(1)

    if not subs:
        print >>sys.stderr, "no usable tracks found"
        sys.exit(1)

    if outfile == "-":
        for s in subs:
            print lastfm.marshaller.dump(s)
    else:
        try:
            writer = lastfm.queue.Writer(outfile, log)
            for s in subs:
                log.info("Sent %s to submit daemon",
                    lastfm.logger.short_name(s))
                print >>writer, lastfm.marshaller.dump(s)
        except IOError:
            print >>sys.stderr, "error: could not write to %s" % outfile
