#!/usr/bin/python

import sys
import time
import getopt

import lastfm
import lastfm.asyaml
import lastfm.logger
import lastfm.queue

if __name__ == "__main__":
    log = lastfm.logger.create_log("lastcdreplay")

    shortopts = 'o:'
    longopts = ['output=']

    try:
        opts, args = getopt.getopt(sys.argv[1:], shortopts, longopts)
    except getopt.GetoptError, e:
        print >>sys.stderr, "error: %s" % e
        sys.exit(1)

    outfile = lastfm.SUBMITD_FIFO

    for opt, arg in opts:
        if opt in ('--output', '-o'):
            outfile = arg

    tracks = []
    for f in [file(n) for n in args] or [sys.stdin]:
        input = lastfm.asyaml.Parser(f.read())
        tracks += input.items

    total_len = 0
    for track in tracks:
        total_len += track.length

    # We will simulate things as if the last track in our input just
    # finished playing right now.
    start = time.time() - total_len

    pos = start
    subs = []
    for track in tracks:
        if track.length >= lastfm.MIN_LEN and track.length <= lastfm.MAX_LEN:
            date = pos + track.length / 2
            try:
                subs.append(lastfm.asyaml.Submission(track=track,
                    time=time.gmtime(date)))
            except ValueError, e:
                print >>sys.stderr, e
                sys.exit(1)
            pos += track.length

    if outfile == "-":
        for sub in subs:
            print sub
    else:
        try:
            writer = lastfm.queue.Writer(outfile, log)
            writer.write(subs)
        except IOError:
            print >>sys.stderr, "error: could not write to %s" % outfile
