.TH lastfm 1
.SH NAME
lastmp, lastcd \- clients for lastfmsubmitd
.SH SYNOPSIS
.B lastmp
.RI [ --debug ]
.RI [ --no-daemon ]
.br
.B lastcd
.RI [ --debug ]
.RI [ --stdout ]
.SH DESCRIPTION
.B lastmp
and
.B lastcd
are clients which send song information to lastfmsubmitd. lastmp connects to
MPD and periodically checks for new songs and how long the current song has
been played. lastcd reads a serialized list of songs that were played on an
offline CD player, such as a car or home stereo, and sends them with estimated
timestamps directly to lastfmsubmitd. Such lists can be generated with
.IR mbget (1).
.SH OPTIONS
.TP
.B \-d, \-\-debug
Log debugging information.
.TP
.B \-n, \-\-no-daemon
Do not fork into the background.
.TP
.B \-o, \-\-stdout
Write the serialized song information to standard output.
.SH FILES
.TP
.B /etc/lastfmsubmitd.conf
The configuration file.
.SH SEE ALSO
.IR mpd (1).
.SH AUTHOR
Decklin Foster <decklin@red-bean.com>.
