.TH lastfm 1
.SH NAME
lastfmsubmitd, lastfmsubmit \- Last.fm submission daemon and helper
.SH SYNOPSIS
.B lastfmsubmitd
.RI [ --debug ]
.RI [ --no-daemon ]
.RI [ --no-network ]
.RI [ --help ]
.br
.B lastfmsubmit
.RI [ --encoding\ ENC ]
.RI [ --artist\ ARTIST ]
.RI [ --title\ TITLE ]
.RI [ --length\ LEN ]
.RI [ --time\ STAMP ]
.RI [ --album\ ALBUM ]
.RI [ --mbid\ TRACKID ]
.RI [ --stdout ]
.RI [ --debug ]
.RI [ --quiet ]
.RI [ --help ]
.SH DESCRIPTION
.B lastfmsubmitd
uses the Last.fm protocol to send information about played songs
to a submission server. If network connectivity is lost or lastfmsubmitd is
shut down, any unsubmitted songs will be saved to disk.
.PP
Song information is collected from one or more music players via a spool
directory. All songs are submitted with the account information provided in
the configuration file.
.PP
.B lastfmsubmit
is a helper program meant to be invoked by music players. It
handles setting the timestamp, encoding data as UTF-8, serializing it to send
to lastfmsubmitd, and locking.
.SH OPTIONS
.TP
.B \-d, \-\-debug
Log debugging information.
.TP
.B \-n, \-\-no-daemon
Do not fork into the background.
.TP
.B \-n, \-\-no-network
Do not attempt to connect to a server, but process submissions anyway.
.TP
.B \-e, \-\-encoding
Use a different encoding than the locale's default to read song information.
.TP
.B \-q, \-\-quiet
Silence any logging information that would normally be printed to stderr.
.TP
.B \-a, \-\-artist
Specify the song's artist name. Artist, title, and length are required for
lastfmsubmitd to actually submit the song.
.TP
.B \-t, \-\-title
Specify the song's title.
.TP
.B \-l, \-\-length
Specify the song's length.
.TP
.B \-i, \-\-time
Specify the time at which the song was played, formatted in UTC as '%Y-%m-%d
%H:%M:%S' (see strptime(3)). If not given, defaults to the current time.
.TP
.B \-b, \-\-album
Specify the song's album name.
.TP
.B \-m, \-\-mbid
Specify the song's MusicBrainz track ID.
.TP
.B \-o, \-\-stdout
Write the serialized song information to standard output instead of the
spool.
.SH FILES
.TP
.B /var/spool/lastfm
The directory where music players should write song information to be
submitted by lastfmsubmitd.
.TP
.B /etc/lastfmsubmitd.conf
The configuration file.
.SH AUTHOR
Decklin Foster <decklin@red-bean.com>.
