.TH lastfm 1
.SH NAME
mbfind, mbget, mbsubmit \- interface to the MusicBrainz database
.SH SYNOPSIS
.B mbget
.RI [ --device\ DEV ]
.RI [ --discid\ ID ]
.RI [ --albumid\ ID ]
.RI [ --freedb ]
.br
.B mbfind
.RI [ --artist\ ARTIST ]
.RI [ --album\ ALBUM ]
.RI [ --verbose ]
.br
.B mbsubmit
.SH DESCRIPTION
.B mbget
prints a listing of the specified album (by default, the disc in /dev/cdrom),
in either a serialized format compatible with
.IR lastfmsubmitd (1)
or a format compatible with FreeDB.
.B mbfind
lists albums in the MusicBrainz database matching the given criteria.
.B mbsubmit
opens a web browser window to submit the disc ID of the disc in /dev/cdrom to
MusicBrainz.
.SH OPTIONS
.TP
.B \-a, \-\-artist
Specify the artist name to search for.
.TP
.B \-b, \-\-album
Specify the album name to search for.
.TP
.B \-v, \-\-verbose
Print all RDF responses read from the server (for debugging purposes).
.TP
.B \-d, \-\-device
Specify the device to read a disc ID from.
.TP
.B \-i, \-\-discid
Specify a disc ID; do not read from any devices.
.TP
.B \-a, \-\-albumid
Specify an album ID; do not read from any devices.
.TP
.B \-f, \-\-freedb
Print output in FreeDB format.
.SH AUTHOR
Decklin Foster <decklin@red-bean.com>.
